import type { Metadata } from "next";
import { Smooch_Sans } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const smoochSans = Smooch_Sans({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${smoochSans.className} antialiased mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 py-6 space-y-14`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
